services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todo
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: todo
      HOST: 0.0.0.0
      PORT: 3001
    depends_on:
      - db
    ports:
      - "3001:3001"   # опционально, но удобно для проверки с хоста
    expose:
      - "3001"
    command: sh -c "npx prisma migrate deploy && node dist/src/index.js"

  web:
    build:
      context: ./web
    environment:
      - VITE_API_URL=http://host.docker.internal:3001
      - VITE_DEV_HOST=localhost
    depends_on:
      - api
    ports:
      - "3000:3000"    # nginx порт (внешний:внутренний)
      - "5173:5173"    # vite dev server для HMR

volumes:
  db_data: